############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "Portfolio/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1


